packages:
  - "packages/client"
  - "packages/proto"
  - "packages/examples"
  - "packages/examples/agent-worker"
  - "packages/examples/trip-planner-worker"
  - "packages/mcp"

# Only allow installing packages that are at least a day old
minimumReleaseAge: 1440
# Allow depending on just published Nzovu packages
minimumReleaseAgeExclude:
  - "@nzovu/*"

ignoreScripts: true
